// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import HomeHero from './HomeHero';
import HomeTopSectionProjects from './HomeTopSectionProjects';
import ProjectCard from './ProjectCard';
import TechStackCard from './TechStackCard';

export {
	CallToAction,
	HomeHero,
	HomeTopSectionProjects,
	ProjectCard,
	TechStackCard,
};

export const components = {
	call_to_action: CallToAction,
	home_hero: HomeHero,
	home_top_section: HomeTopSectionProjects,
	project_card: ProjectCard,
	tech_stack_card: TechStackCard,
};
