// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import ContactForm from './ContactForm';
import HomeHero from './HomeHero';
import ProjectCard from './ProjectCard';
import ProjectDescriptionCard from './ProjectDescriptionCard';
import ProjectHero from './ProjectHero';
import ProjectImageCard from './ProjectImageCard';
import TechStackCard from './TechStackCard';

export {
	CallToAction,
	ContactForm,
	HomeHero,
	ProjectCard,
	ProjectDescriptionCard,
	ProjectHero,
	ProjectImageCard,
	TechStackCard,
};

export const components = {
	call_to_action: CallToAction,
	contact_form: ContactForm,
	home_hero: HomeHero,
	project_card: ProjectCard,
	project_description_card: ProjectDescriptionCard,
	project_hero: ProjectHero,
	project_image_card: ProjectImageCard,
	tech_stack_card: TechStackCard,
};
